spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc: trace
    dev.bogdanjovanovic: trace

url:
  redis:
    counter-key: url:counter
