spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      concurrency: 3

logging:
  level:
    org.springframework.jdbc: trace
    dev.bogdanjovanovic: trace

redis:
  lru:
    port: 6379
  aof:
    port: 6380
    counter-key: url:counter
